services:
  chatbot:
    build: .
    image: utarn/chatbot
    restart: always
    ports:
      - "8003:80"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"

  database:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot-lite
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: